config/routes.rb
Rails.application.routes.draw do

  devise_for :users
resources :questions do
  resources :answers, shallow: true do
    patch :make_best, on: :member
  end
end
  resources :attachments, only: :destroy

root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments

  validates :question_id, :user_id, :body,  presence: true

  default_scope { order(best: :desc, created_at: :asc) }

  def make_best
    Answer.transaction do
      self.question.answers.update_all(best: false)
      self.update!(best: true)
    end
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader

  def file_name
    file.try(:file).try(:filename)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user

  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments

  validates :title, :body, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers

  def author_of?(obj)
    true if id == obj.user_id
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_question, only: [:new, :create]


  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @answer = Answer.find(params[:id])
    if current_user && current_user.author_of?(@answer)
      @answer.destroy
      @notice = "Answer succesfully deleted!"
      else
      @notice = "You are not author"
    end
    redirect_to @answer.question, notice: @notice
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)

  end

  def make_best
    @answer = Answer.find(params[:id])
    @question = @answer.question

    if current_user.author_of?(@question)
      @answer.make_best
    end
  end
  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
   params.require(:answer).permit(:body, attachments_attributes: [:file, :_destroy, :id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @attachment = Attachment.find(params[:id])
    if current_user && current_user.author_of?(@attachment.attachable)
      @attachment.destroy
      @notice = "File succesfully deleted!"
    else
      @notice = "You are not author"
    end

  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :question_load, only:[:show, :destroy, :update]

  def index
    @questions = Question.all
  end

  def show
  @answer = @question.answers.build
  @answer.attachments.build
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path
    else
      redirect_to @question, notice: 'You are not the author'
    end
  end

  def update
    @question.update(question_params)
  end


  private

  def question_load
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat message
               concat content_tag(:span, '', class: "close glyphicon glyphicon-remove", data: { dismiss: 'alert' })
             end)
    end
    nil
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  div.answer-count id="answer_#{answer.id}"
    p.answer-body = answer.body
    p.answer-attachments Attachments:
    p
      ul
        = render answer.attachments

    - if answer.best?
      p.best-answer Best answer
    - if current_user && current_user.author_of?(answer.question) && !answer.best?
      p = link_to 'Choose as Best', make_best_answer_path(answer), method: :patch, remote: true
    - if current_user && current_user.author_of?(answer)
      p= link_to 'Delete answer', answer_path(answer), method: :delete
      p= link_to 'Edit', '#edit', id: "#{answer.id}", class: 'edit-answer-link'
      p= form_for answer, remote: true, html: {id: "edit-answer-#{answer.id}"} do |f|
        = f.label :body, 'Answer'
        = f.text_area :body
        = f.fields_for :attachments do |a|
          //= render 'attachments/attachment_form', f: a
        .links
          = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_form'
        = f.submit 'Save'
  hr

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/make_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
<% @answer.errors.full_messages.each do |message| %>
$('.answer-errors').html('<%= j message %>');
<% end %>
<% else %>
$('#answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');
//$('#answer_<%= @answer.id %> p.answer-body').text(<%= j  @answer.body %>');
//$('#answer_<%= @answer.id %> p.answer-attachments').html('<%= j render  @answer.attachments %>');
$('form#edit-answer-<%= @answer.id %>').hide();
<% end %>

app/views/attachments/_attachment.html.slim
.attachment
  li id= "attachment-#{attachment.id}"
    = link_to attachment.file_name, attachment.file.url
    -  if current_user && current_user.author_of?(attachment.attachable)
      br
      = link_to "Delete file", attachment_path(attachment), method: :delete, remote: true

app/views/attachments/_attachment_form.html.slim
.nested-fields
  .fields
    = f.label :file
    = f.file_field  :file
  = link_to_remove_association "remove file", f

app/views/attachments/destroy.js.erb
$('li#attachment-' + '<%= @attachment.id %>').remove();

app/views/layouts/_header.html.slim
nav class="navbar navbar-inverse navbar-fixed-top"
  div class="container"
    div class="navbar-header"
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span class="sr-only" Navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"

      a class="navbar-brand" href="/" Stack Overflow

    div id="navbar" class="navbar-collapse collapse"
      ul class="nav navbar-nav"
        li.root: a<> href="#{questions_path}" Questions
        //li: a<> href="#" Users


      /form class="navbar-form navbar-left .search-cont" role="search"
      /  .input-group
      /    input.form-control.search-form aria-label="..." placeholder="find it..." type="text" /
      /    .input-group-btn
      /      button.btn.btn-default.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
      /        | Search in
      /        span.caret<>
      /      ul.dropdown-menu.dropdown-menu-right
      /        li: a href="#" class="drp-search" all objects
      /        - Search::INDEXES.each do |i|
      /          li: a href="#" class="drp-search" id="drp-search-in_#{i}" = i


      ul class="nav navbar-nav navbar-right"
        -if current_user
          li class="dropdown"
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
              span class="glyphicon glyphicon-cog"
              span<> Settings
              span class="caret"
            ul class="dropdown-menu dropdown-right" role="menu"
              li: a href="#" Profile
              li: a href="#" Change password
          li
            a href="#{destroy_user_session_path}" rel="nofollow" data-method="delete"
              span class="glyphicon glyphicon-off"
              span<> Sign out
        -else
          li = link_to 'Sign In', new_user_session_path
          li: span or
          li =link_to 'Sign Up',  new_user_registration_path

app/views/layouts/application.html.slim
doctype 5
html
  head
    title QNA
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    link rel="icon" href="../../favicon.ico"
    /[if lt IE 9]
      script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body role="document"
    = render 'layouts/header'
  div class="container theme-showcase body-cont" role="main"
    = flash_messages
    = yield

app/views/questions/_question.html.slim
h4
-if question.persisted?
  div.question-count id="question_#{question.id}"
    p.question-title = question.title
    p.question-body = question.body
    p Attachments:
    p
      ul
        = render question.attachments

    - if current_user && current_user.author_of?(question)
      p= link_to 'Edit','#edit', id: "#{question.id}", class: 'edit-question-link'
      p= form_for question, remote: true, html: {id: "edit-question-#{question.id}"} do |f|
        = f.label :title, 'Title'
        = f.text_area :title
        br
        = f.label :body, 'Body'
        = f.text_area :body
        p= fields_for :attachments do |a|
          .links
            = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_form'
        br
        = f.submit 'Save'
hr

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path, class: "btn btn-success"
hr
- @questions.each do |question|
  div
    = link_to question.title, question_path(question)
  hr

app/views/questions/new.html.slim
.row
  = form_for @question do |f|
    .col-md-1
      = f.label :title
    .col-md-11
      = f.text_field :title
    .clearfix style="margin-bottom: 5px;"
    .col-md-1
      = f.label :body
    .col-md-11
      = f.text_area :body
    p Attachment:
    p
      = f.fields_for :attachments do |a|
        = a.label :file
        = a.file_field :file
    div
      = f.submit 'Create', class: "btn btn-success"

app/views/questions/show.html.slim
.question
  = render @question
hr
.answers
  = render @question.answers


-if current_user
  .row
    = form_for [@question, @answer], remote: true  do |f|
      .col-md-1
        = f.label :body, 'Your Answer'
      .answer-errors
      .col-md-11
        = f.text_area :body
      p
        = f.fields_for :attachments do |a|
          = a.label :file
          = a.file_field :file
      div
        = f.submit 'Create answer', class: "btn btn-success"


hr
-if current_user && current_user.author_of?(@question)
  p= link_to 'Delete question', question_path(@question), method: :delete, class: "btn btn-danger"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
<% @question.errors.full_messages.each do |message| %>
$('.question-errors').html('<%= j message %>');
<% end %>
<% else %>
$('#question_<%= @question.id %>').replaceWith('<%= j render @question %>');
//$('#question_<%= @question.id %> p.question-title').text('<%=  @question.title %>');
//$('#question_<%= @question.id %> p.question-body').text('<%=  @question.body %>');
$('form#edit-question-<%= @question.id %>').hide();
<% end %>